version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - house-net

  api:
    build: .
    container_name: house-api
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    networks:
      - house-net
    environment:
      MONGO_URI: "mongodb://mongo:27017/house_db"

volumes:
  mongo-data:

networks:
  house-net:
    driver: bridge
